using System;

namespace Kosson.KORM
{
	/// <summary>
	/// Adds database index on a table.
	/// </summary>
	[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
	public class IndexAttribute : Attribute
	{
		/// <summary>
		/// Determines whether index is unique.
		/// </summary>
		public bool IsUnique { get; set; }

		/// <summary>
		/// Gets or sets index name.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Gets or sets columns of the index key. Names can be provided as a column identifiers or property identifiers.
		/// </summary>
		public string[] Fields { get; set; }

		/// <summary>
		/// Gets or sets columns included in index leaf nodes, but not in index key. Names can be provided as a column identifiers or property identifiers.
		/// </summary>
		public string[] IncludedFields { get; set; }

		/// <summary>
		/// Adds database index on a table.
		/// </summary>
		/// <param name="indexName">Database name of the index.</param>
		/// <param name="indexFields">Columns or properties names of the index key.</param>
		public IndexAttribute(string indexName, params string[] indexFields)
		{
			Name = indexName;
			Fields = indexFields;
		}
	}

	/// <summary>
	/// Adds database index on a table.
	/// </summary>
	public static class Index
	{
		/// <summary>
		/// Adds a unique database index on a table with a autogenerated name.
		/// </summary>
		public sealed class UniqueAttribute : IndexAttribute
		{
			/// <summary>
			/// Adds a unique database index on a table with a autogenerated name..
			/// </summary>
			/// <param name="indexFields">Columns or properties names of the index key.</param>
			public UniqueAttribute(params string[] indexFields)
				: base("UIDX_{0}_" + String.Join("", indexFields), indexFields)
			{
				IsUnique = true;
			}
		}

		/// <summary>
		/// Adds a nonunique database index on a table with a autogenerated name.
		/// </summary>
		public sealed class NonUniqueAttribute : IndexAttribute
		{
			/// <summary>
			/// Adds a nonunique database index on a table with a autogenerated name.
			/// </summary>
			/// <param name="indexFields">Columns or properties names of the index key.</param>
			public NonUniqueAttribute(params string[] indexFields)
				: base("IDX_{0}_" + String.Join("", indexFields), indexFields)
			{
			}
		}
	}
}
